export const DESTINATIONFROM = 'ADD/DESTINATIONFROM';
export const DESTINATIONTO = 'ADD/DESTINATIONTO';
export const DATEFROM = 'ADD/DATEFROM';
export const GUEST = 'ADD/GUEST';
export const FLIGHTTYPECLASS = 'ADD/FLIGHTTYPECLASS';
export const SUBMIDTA = 'ADD/SUBMIDTA';